# https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command
services:
  dev-server:
    build:
      dockerfile: ./e2e-cypress/Dockerfile.dev-server.local
      context: ..
  cypress:
    build:
      dockerfile: ./e2e-cypress/Dockerfile.cypress.run.local
      context: ..
    volumes:
      - ./snapshots:/app/e2e-cypress/snapshots
    environment:
      # You need to pass the CYPRESS_baseUrl variable, otherwise Cypress tries to find
      # dev server at http://127.0.0.1:4200
      - CYPRESS_baseUrl=http://dev-server:4200
    depends_on:
      - dev-server
