name: Tour of heroes

on:
  workflow_dispatch:
  pull_request:
    types: [opened]
    branches: ['develop']
    # paths:
    #   - .github/workflows/tour-of-heroes.yml
    #   - ./tour-of-heroes/**
  push:
    branches: ['develop']
    # paths:
    #   - .github/workflows/tour-of-heroes.yml
    #   - ./tour-of-heroes/**

permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  pull-requests: write

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./tour-of-heroes
        run: npm ci
      - name: Run tests
        working-directory: ./tour-of-heroes
        run: npm run test:unit:ci

  # TODO: возможно разбить coverage и report, но тогда и кэшнуть зависимости   
  test-unit-report:
    needs: [test-unit]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./tour-of-heroes
        run: npm ci
      - name: Run tests with coverage and timing reports
        working-directory: ./tour-of-heroes
        run: npm run test:unit:report
      - name: Create test results report check
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-unit-results         
          path: ./tour-of-heroes/report/test-results.xml
          reporter: jest-junit
      - name: Create test results annotations, PR comment and workflow summary
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ./tour-of-heroes/report/test-results.xml
          comment_title: "Unit Test Results"
          job_summary: true
          check_run: false
      - name: Upload coverage report directory
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifact
          path: ./tour-of-heroes/coverage
          if-no-files-found: error
          retention-days: 3
